[package]
name = "redmine_api"
version = "0.0.1"
authors = ["Florian Sommer <fsommer1986@gmail.com>"]

[dependencies]
error-chain = "0.10"
reqwest = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
